package com.xiaobai.ioa.model.po;
// Generated 2018-1-17 10:26:22 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable
{

	private long did;
	private String dname;
	private String description;
	private Set users = new HashSet(0);

	public Department()
	{
	}

	public Department(long did)
	{
		this.did = did;
	}

	public Department(long did, String dname, String description, Set users)
	{
		this.did = did;
		this.dname = dname;
		this.description = description;
		this.users = users;
	}

	public long getDid()
	{
		return this.did;
	}

	public void setDid(long did)
	{
		this.did = did;
	}

	public String getDname()
	{
		return this.dname;
	}

	public void setDname(String dname)
	{
		this.dname = dname;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public Set getUsers()
	{
		return this.users;
	}

	public void setUsers(Set users)
	{
		this.users = users;
	}

}
