package com.xiaobai.ioa.model.po;
// Generated 2018-1-17 10:26:22 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable
{

	private long pid;
	private String pname;
	private String description;
	private Set users = new HashSet(0);

	public Post()
	{
	}

	public Post(long pid)
	{
		this.pid = pid;
	}

	public Post(long pid, String pname, String description, Set users)
	{
		this.pid = pid;
		this.pname = pname;
		this.description = description;
		this.users = users;
	}

	public long getPid()
	{
		return this.pid;
	}

	public void setPid(long pid)
	{
		this.pid = pid;
	}

	public String getPname()
	{
		return this.pname;
	}

	public void setPname(String pname)
	{
		this.pname = pname;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public Set getUsers()
	{
		return this.users;
	}

	public void setUsers(Set users)
	{
		this.users = users;
	}

}
